### ISSUE TITLE
Unable to Connect to Softlayer API

### ISSUE THREAD

**Issue by sriramanne2** [softlayer/softlayer-python#1005]
**Please triple-check to make sure that you have properly masked out user credentials like usernames, passwords and API keys before submitting your issue**

### Expected Behavior
Script usually generates a report collecting information from various API used internally.

### Actual Behavior
Script is getting stuck while execution. Other python scripts are executing. 
[Testing.zip](https://github.com/softlayer/softlayer-python/files/2202278/Testing.zip)
Experiencing same issue with all 3 scripts in the archive.

### Environment Information
Operating System: Centos 7
softlayer-python version (`slcli --version`): slcli (SoftLayer Command-line), version 5.4.4

**Comment by allmightyspiff** [comment]
Please provide an error or something that shows what problem you are having.

**Comment by sriramanne2** [comment]
The execution just gets stuck and nothing happens.

**Comment by sriramanne2** [comment]
Attached a screenshot below. 
![error](https://user-images.githubusercontent.com/41338127/42830155-b84c4b74-89b8-11e8-9b14-8d3a18853ae7.PNG)

**Comment by acamacho82** [comment]
@sriramanne2 I don't think this is a connection issue from the python client, I just added a code line to print the results and the API returns the list of virtual guests so I recommend you to debug your script in order to find the root cause of your issue.

Make sure the file ~/.softlayer exists in your system if you are not setting your credentials in the script.

![image](https://user-images.githubusercontent.com/6937170/43479981-e988ff3a-94cf-11e8-96de-e91c5efc93f2.png)

I realized your are using masks and I don't think they really works because the way you built the mask isn't seems to be correct, I suggest you to check the links below if that is the case, those are some examples which show how to build the mask in python

https://softlayer.github.io/python/list_customers.py/
https://softlayer.github.io/python/list_images_os_manager.py/
https://stackoverflow.com/questions/44940582/softlayer-api-how-to-get-the-static-subnet-belongs-to-which-vsi
https://stackoverflow.com/questions/38491538/internal-server-error-when-get-the-tags-of-the-virtual-guest
