### ISSUE TITLE
[feature request] Storage size

### ISSUE THREAD

**Issue by PedroMVM** [softlayer/softlayer-python#1031]
I am trying to get storage size and used size, but it seems that it is not possible with current Python library. Virtual server has a property called _blockDevices_, which list all storage with the following properties: _bootableFlag_, _createDate_, _device_, _diskImageId_, _guestId_, _hotPlugFlag_, _id_, _modifyDate_, _mountMode_, _mountType_, _statusId_, and _uuid_.

### Expected Behavior
Each device should have storage properties like _size_, _used_, and _available_.

### Actual Behavior
No properties for storage size.

### Environment Information
Operating System: Any
softlayer-python version (`slcli --version`): 5.4.4

**Comment by acamacho82** [comment]
The API returns the _'size'_ and _'used'_ values for **file storage** devices, and only _'size'_ for **block storage**, and for _'available'_ value I recommend you calculate it based on  _'size'_ and _'used'_.

In order to retrieve that information you can call the service [SoftLayer_Network_Storage ](https://softlayer.github.io/reference/services/SoftLayer_Network_Storage/) with masks as following.

```python
 client = SoftLayer.Client()
 storage_id=33334444

 result = client['Network_Storage'].getObject(id=storage_id, mask="bytesUsed,totalBytesUsed")
 print(result)
```

_'bytesUsed'_ and _'totalBytesUsed'_ are in bytes so you will need to convert them to MB or GB if required.

You can also use [FileStorageManager](https://softlayer-python.readthedocs.io/en/latest/api/managers/file.html) and [BlockStorageManager](https://softlayer-python.readthedocs.io/en/latest/api/managers/block.html) classes in case you are working with python managers

``` python
 client = SoftLayer.Client()
 manager = FileStorageManager(client)

 storage_id=33334444 

 result = manager.get_file_volume_details(volume_id=storage_id)
 print(result)
```

And on SLCLI you can use the commands `slcli file volume-detail` and `slcli block volume-detail`.

```
$ slcli file volume-detail 33334444
:..........................:...............................................................:
:                     Name : Value                                                         :
:..........................:...............................................................:
:                       ID : 33334444                                                      :
:                 Username : SL02SEV######_63                                              :
:                     Type : ENDURANCE                                                     :
:            Capacity (GB) : 50GB                                                          :
:               Used Space : 6GB                                                           :
:                     IOPs : 102                                                           :
:           Endurance Tier : READHEAVY_TIER                                                :
:              Data Center : dal13                                                         :
:                Target IP : xxx-dal1301x-xx.xxx.networkxxx.com                            :
:            Mount Address : xxx-dal1301x-xx.xxx.networkxxx.com:/SL02SEV######_63/data01   :
: # of Active Transactions : 0                                                             :
:          Replicant Count : 0                                                             :
:..........................:...............................................................:

```

**Comment by acamacho82** [comment]
There is no way to retrieve the disk usage or available space since these information isn't stored in the softlayer database, see [get-disk-usage-from-softlayer-api](https://stackoverflow.com/questions/41935264/get-disk-usage-from-softlayer-api).

On the other hand, you should be able to retrieve the disk size through the property [diskImage.capacity](https://softlayer.github.io/reference/datatypes/SoftLayer_Virtual_Disk_Image/#capacity), try with the following slcli command:

`slcli --format=json call-api Virtual_Guest getBlockDevices --id=55533999 --mask="id,diskImage"`

On [softlayer-vsi-total-sotrage](https://stackoverflow.com/questions/44032154/softlayer-vsi-total-sotrage)  there is an example in python which could help you to retrieve the disk size of each _blockDevice_ into the virtual server.
