### ISSUE TITLE
getting ('SOAP-ENV:Server', 'Internal Error') when calling getAllBillingItems()

### ISSUE THREAD

**Issue by ashringa** [softlayer/softlayer-python#1124]
**Please triple-check to make sure that you have properly masked out user credentials like usernames, passwords and API keys before submitting your issue**

error calling Billing_Item:
I am looking to download detailed billing information through API using Python. I am following this article - https://softlayer-api-python-client.readthedocs.io/en/latest/api/client/

But I get ('SOAP-ENV:Server', 'Internal Error') when I run the below give code snippet

Code snippet:
client = SoftLayer.Client(username=USERNAME, api_key=API_KEY)
accountService = client['SoftLayer_Account']
try: 
result = accountService.getAllBillingItems()
print(result)

except SoftLayer.SoftLayerAPIError as e:
print((e.faultCode, e.faultString))
exit(1)

### Expected Behavior
Returns list of billing item

### Actual Behavior:
Error ('SOAP-ENV:Server', 'Internal Error')

### Environment Information
Operating System: macOS Mojava version 10.14
softlayer-python version (`slcli --version`):SoftLayer version is 5.7.0

**Comment by acamacho82** [comment]
This is not an python client issue, usually the `Internal Error` messages from the API are because you are trying to retrieve a lot of data with only one request, on this case it is recommended to use resultLimits (pagination), masks and filters.

for example to retrieve the first 50 items:
```python
result = accountService.getAllBillingItems(limit=50, offset=0)
```
and for the next 50:

```python
result = accountService.getAllBillingItems(limit=50, offset=50)
```

References:
https://sldn.softlayer.com/article/exception-handling-softlayer-api/
https://sldn.softlayer.com/article/using-result-limits-softlayer-api/
https://sldn.softlayer.com/article/object-filters/
https://sldn.softlayer.com/article/object-masks/

**Comment by allmightyspiff** [comment]
The latest version of the softlayer-python client can automatically iterate through large data sets like this:

`client.call('Account','getAllBillingItems', iter=True)`

Hope that helps.
