### ISSUE TITLE
The call to API will ignore the offset when setting limit to 1

### ISSUE THREAD

**Issue by zhuzixiao** [softlayer/softlayer-python#1255]
We are trying to use SOAP API to get SoftLayer escalation tickets. We make the call to the service like following. 
```
client["Escalation"].call( "getAllObjects",
        filter={ #some filter options# },
        mask=MASK,  
        limit=1, offset=10000)
```
Since we need quite a large amount of data (a really long MASK), we have to set the limit to 1 otherwise we will receive errors like: `SoftLayer.exceptions.TransportError: TransportError(500): 500 Server Error: Internal Server Error for url: https://192.168.65.8/v3/internal/xmlrpc/SoftLayer_Escalation.`

### Expected Behavior
By setting limit to 1 and increase the offset, we hope to get the data record one by one.

### Actual Behavior
Actually, the API will ignore the offset and always return the first record matching the filtering options.

### Environment Information
Operating System: MacOS 10.15.4
softlayer-python version (`slcli --version`): 5.8.1

**Comment by allmightyspiff** [comment]
This is a bug with the `SoftLayer_Escalation::getAllObjets` API, NOT with the softlayer-python library. You should be able to reproduce this with a normal CURL call.  This is something you'd need to escalate internally since it is an internal api call.

Some suggestions though. If you are just getting Escalations individually, I'd HIGHLY recommend doing this API call in two stages.

1. Set your mask to just get the ID + any fields you are filtering by, and get all the ids with SoftLayer_Escalation::getAllObjets
2. For each of those escalation ids, call SoftLayer_Escalation::getObject with your large object mask. 

When you call SoftLayer_Escalation::getAllObjets with a large object mask, every time you make that api call, the database has to do a full table scan on all the tables in your object mask, which is very expensive computation wise. 
SoftLayer_Escalation::getObject however doesn't require that, since you are selecting the escalation by id, the database can use the primary key to get the result, saving a lot of time.

Hope that helps answer your question.

**Comment by zhuzixiao** [comment]
@allmightyspiff Great thanks for your reply.

Actually your method is what we are tring to work around. However we still get the transport error, which usually indicates too much data.

**Comment by allmightyspiff** [comment]
Which part is giving you the transport error?

If your filter is still giving you more than 10000 results, you might want to fine tune it some more. Perhaps adding a filter by createDate and go month by month (or day by day if needed)

If this call is generating a timeout error, then you would need to tune down your filter and make multiple calls to getAllObjects
```python
client["Escalation"].call( "getAllObjects",
        filter={ #some filter options# },
        mask="mask[id]",
```

**Comment by zhuzixiao** [comment]
@allmightyspiff Thanks a lot.
We are calling the method that you suggested: 

```
def get_escalation(client, id, **kwargs):
    escalationSvc = client["Escalation"]
    result = escalationSvc.call("getObject", id=id, mask=MASK)

    return result
```

We get the escalation ticket one by one, but the mask is really large. I think the data maybe still exceed the limit.

```
 File "/Users/zixiaozhuibm/Library/Python/2.7/lib/python/site-packages/SoftLayer/API.py", line 371, in call
    return self.client.call(self.name, name, *args, **kwargs)
  File "/Users/zixiaozhuibm/Library/Python/2.7/lib/python/site-packages/SoftLayer/API.py", line 274, in call
    return self.transport(request)
  File "/Users/zixiaozhuibm/Library/Python/2.7/lib/python/site-packages/SoftLayer/transports.py", line 247, in __call__
    raise exceptions.TransportError(ex.response.status_code, str(ex))
SoftLayer.exceptions.TransportError: TransportError(500): 500 Server Error: Internal Server Error for url: https://192.168.65.8/v3/internal/xmlrpc/SoftLayer_Escalation
```
