### ISSUE TITLE
`slcli firewall detail` do not find standard firewall to display its info

### ISSUE THREAD

**Issue by BrianSantivanez** [softlayer/softlayer-python#1643]
> Reminder: No username or APIkeys should be added to these issues, as they are public.

**Describe the bug**
When `slcli firewall detail` command is set with an standard (vs or server) firewall that exists the command display a message saying that the firewall was not found

**Expected behavior**
The command should display the firewall rules

**Screenshots**
![image](https://user-images.githubusercontent.com/78806346/168892172-379d3077-9152-462e-b799-51aca89e6ec4.png)

**Version**
![image](https://user-images.githubusercontent.com/78806346/168892239-21c88880-bcab-4235-a322-d4666c33f8e2.png)

**Comment by allmightyspiff** [comment]
I think the firewall command might need a complete overhaul, as the firewall stuff has changed a LOT since the original command was written.

Ideally our command should work similar to how the portal displays information https://cloud.ibm.com/netsec/firewalls#multiVlan

Mutli Vlan and Single Server firewalls are still available, but single vlan firewalls are no longer a product (although it exists since some customers still have them). We do not need to support single vlan firewalls going forward though, just multi-vlan, and single server.

**Comment by caberos** [comment]
update the firewall list command to same to Ibmcloud page and add the new multi Vlan table with all data information to return this
![Uploading image.png…]()
