### ISSUE TITLE
error when "import SoftLayer"

### ISSUE THREAD

**Issue by nicklee76** [softlayer/softlayer-python#486]
Hi all,

I am getting following error on "import SoftLayer".  Could anyone help me with this problem?  Thanks in advance!
---
$ python 
Python 2.7.8 (v2.7.8:ee879c0ffa11, Jun 29 2014, 21:07:35) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import SoftLayer
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/SoftLayer/__init__.py", line 19, in <module>
    from SoftLayer.API import *  # NOQA
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/SoftLayer/API.py", line 11, in <module>
    from SoftLayer import config
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/SoftLayer/config.py", line 12, in <module>
    from SoftLayer import utils
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/SoftLayer/utils.py", line 21, in <module>
    xmlrpc_client = six.moves.xmlrpc_client
AttributeError: '_MovedItems' object has no attribute 'xmlrpc_client'
>>>

**Comment by sudorandom** [comment]
Try updating your version of the 'six' library.

```python
pip install six
```

**Comment by nicklee76** [comment]
@sudorandom 
I tried the update but my 'six' was up to date already. 

---
$ pip install six --upgrade
Requirement already up-to-date: six in /Library/Python/2.7/site-packages

$ python
Python 2.7.8 (v2.7.8:ee879c0ffa11, Jun 29 2014, 21:07:35) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import SoftLayer
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/SoftLayer/__init__.py", line 19, in <module>
    from SoftLayer.API import *  # NOQA
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/SoftLayer/API.py", line 11, in <module>
    from SoftLayer import config
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/SoftLayer/config.py", line 12, in <module>
    from SoftLayer import utils
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/SoftLayer/utils.py", line 21, in <module>
    xmlrpc_client = six.moves.xmlrpc_client
AttributeError: '_MovedItems' object has no attribute 'xmlrpc_client'

**Comment by sudorandom** [comment]
This is totally something environmental. I noticed that your paths aren't matching up. When trying to upgrade six the path is **/Library/Python/2.7/site-packages** but in the traceback it is referencing **/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages**. I would try uninstalling both packages (six and the softlayer bindings) and installing them again the same way.

**Comment by mattpangaro** [comment]
Hi all. I'm getting the same thing trying to use the new SL API. My old calls with a local SoftLayer.API library were working, but with pip installed softlayer/six, I get this:
Traceback (most recent call last):
  File "./softlayer-get-server-info.py", line 5, in <module>
    import SoftLayer
  File "/Library/Python/2.7/site-packages/SoftLayer/__init__.py", line 19, in <module>
    from SoftLayer.API import *  # NOQA
  File "/Library/Python/2.7/site-packages/SoftLayer/API.py", line 12, in <module>
    from SoftLayer import config
  File "/Library/Python/2.7/site-packages/SoftLayer/config.py", line 12, in <module>
    from SoftLayer import utils
  File "/Library/Python/2.7/site-packages/SoftLayer/utils.py", line 19, in <module>
    xmlrpc_client = six.moves.xmlrpc_client  # pylint: disable=E1101,C0103
AttributeError: '_MovedItems' object has no attribute 'xmlrpc_client'

I'm on Mac OSX 10.10.2 with python 2.7.9. I've tried pip uninstalling and reinstalling both six and softlayer. I don't seem to have the muddled paths mentioned above. The only location for the site-packages on my machine is /Library/Python/2.7

Thanks in advance for any ideas on how to get past this.

**Comment by sudorandom** [comment]
This appears to be an OSX issue with either mavericks install itself or an update after the fact. If you're not using something like brew to install your own version of Python, I'm not sure how to help but there's still a couple things to try that I'll go through below. If you are using brew, this is likely your best guide to fixing this issue: https://gist.github.com/goldsmith/7163055

There's a high likelihood that there's a version of the six library installed somewhere on your machine that is out of date and was never uninstalled when you thought it was. Last time I checked, if a module was installed with easy_install or through some other method then it cannot be uninstalled using `pip uninstall module_name`.

Since the issue has been in the python shell, let's debug the issue there. If you have `six` and `softlayer` uninstalled using `pip uninstall softlayer six` then `import six` in a python shell should not work. I predict that it DOES work on both of your machines because it already exists in a path you weren't expecting (in a version that causes the attribute error referenced above). There are a couple standard ways to find the file path and the version of a module in python:
```
$ python
>>> import six
>>> six.__version__
'1.9.0'
>>> six.__file___
'/home/kevin/venv/local/lib/python2.7/site-packages/six.pyc'
```

If the version is less than 1.9.0 or the file path is not what you expect, delete six and re-install it with pip.

```
$ rm /home/kevin/venv/local/lib/python2.7/site-packages/six.py
$ rm /home/kevin/venv/local/lib/python2.7/site-packages/six.pyc
$ rm -rf /home/kevin/venv/local/lib/python2.7/site-packages/six-1.9.0-py2.7.egg-info
$ pip install six
```

Alternatively to all of this, you can use virtual environments to isolate your python libraries or use brew which should simplify a lot of these path issues as described in the link above.

**Comment by laurent-martin** [comment]
Environment: Mac OS X Yosemite
Had the same error, problem was a duplicate older "six" lib.
cd /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/
rm six.py*

and problem is gone.

**Comment by underscorephil** [comment]
Closing due to lack of action
