### ISSUE TITLE
server list important columns missing in 4.0

### ISSUE THREAD

**Issue by jravetch** [softlayer/softlayer-python#547]
After upgrading to version 4, I lost the ability to see the owner/cpu/memory of each server when using list.  Owner is very important, as it allows me to see quickly what users provisioned which machines.  It also also allows me to see which servers are in the Spare Pool.  Cpu and memory columns allow me to quickly see the cpu/memory allocated of each server.  If you can please bring back these colums ASAP, I would greatly appreciate it.  Moreover, would it be possible to add a spare pool filter so that I can only list servers that are in the spare pool?

**Comment by sudorandom** [comment]
@jravetch The owner column was removed due to performance concerns. The way that data has to be masked in adds 2 full seconds to a typical virtual server listing. Additionally, the amount of horizontal space that we have now is very limited even considering a 140 terminal size. That's why CPU and memory were cut. I can see argument for those being more important than having the ip addresses. The command was modeled after the portal UI, but there's obviously different concerns and limitations for a CLI than a web UI.

There's an issue which should allow you to show all the columns that you want while maintaining performance and UX for a typical case: https://github.com/softlayer/softlayer-python/pull/503. I intend to help out with that when I have the time.

Until then, you can either downgrade to version 3.3.1.
```
pip uninstall softlayer
pip install softlayer==3.3.1
``` 

or you can use the new call-api command to mask in exactly the data that you want. Unfortunately, the data is fairly nested (which probably explains the performance issues), so the best way I've found to show this data is by using the json format:
```bash
slcli --format=json call-api Account getVirtualGuests --mask="id,maxCpu,maxMemory,hostname,billingItem[id,orderItem[id,order[id,userRecord[id,username]]]]"
```

but the normal table version might work better for you if your screen is big enough to avoid line wrapping:
```
slcli call-api Account getVirtualGuests --mask="id,maxCpu,maxMemory,hostname,billingItem[id,orderItem[id,order[id,userRecord[id,username]]]]"
```

**Comment by sudorandom** [comment]
Here are the hardware equivalents:
```
slcli --format=json call-api Account getHardware --mask="id,processorPhysicalCoreAmount,memoryCapacity,hostname,billingItem[id,orderItem[id,order[id,userRecord[id,username]]]]"
```
and
```
slcli call-api Account getHardware --mask="id,processorPhysicalCoreAmount,memoryCapacity,hostname,billingItem[id,orderItem[id,order[id,userRecord[id,username]]]]"
```

**Comment by jravetch** [comment]
@sudorandom Ok thanks this is useful.  Probably you should mention this in the Changelog, as I was caught off guard.   Any thoughts on my second question regarding filtering servers that are in the Spare Pool?

**Comment by underscorephil** [comment]
@jravetch @sudorandom 

I do not believe there is currently a way to pass object filters into the CLI tool.

This is a way you could do it with a raw call: https://gist.github.com/underscorephil/4cc78276363a7782453b

**Comment by sudorandom** [comment]
This issue created the ability to have custom columns: https://github.com/softlayer/softlayer-python/pull/608. The next step to take with this is to have the columns that users select influence the mask that is used when making the API call. That way, the owner (and many other) columns can still be used but it would not influence the performance of the default usage.

**Comment by jravetch** [comment]
@sudorandom Sorry it has taken me a while to test this feature.  Aside from the default columns, when I add a non default column the result is blank.  Just a '-' is listed next to each hostname,id.

**Comment by sudorandom** [comment]
@jravetch can you give an example? I can't seem to reproduce.

**Comment by jravetch** [comment]
@sudorandom 

Here's an example:

slcli server list --columns=id,hostname,cores                                         
:........:.......................................:.......:
:   id   :                hostname               : cores :
:........:.......................................:.......:
: xxx  :          yyy         :   -   :
: xxx  :          yyy         :   -   :
: xxx :          yyy         :   -   :
: xxx :         yyy         :   -   :

I've removed the actual server ID and hostname, but as you can see, I've added cores as a new column, but only a '-' id displayed there.

**Comment by sudorandom** [comment]
@jravetch sorry for the delayed response. The current version should error in the case you described in your last message. The help text shows the available options for the `--columns` keyword.

```
  --columns TEXT         Columns to display. Options: guid, primary_ip,
                         backend_ip, datacenter, action, power_state,
                         created_by, tags
```

One thing that isn't yet well explained is that you can also include masks. For example, 'cores' would actually be processorCoreAmount in the API (can be referenced via http://sldn.softlayer.com/reference/datatypes/SoftLayer_Hardware). Therefore, this example should work: `slcli server list --columns=id,hostname,processorCoreAmount`

**Comment by jravetch** [comment]
@sudorandom I tried your example and still get just a '-' for the processCoreAmount
