### ISSUE TITLE
How upload files using Object Storage Client

### ISSUE THREAD

**Issue by crackxlash** [softlayer/softlayer-python#637]
Hello, someone will have some examples?

**Comment by underscorephil** [comment]
Howdy @crackxlash!

The softlayer-python project does not have support for Object Storage. Are you looking for examples for a different client?

**Comment by sudorandom** [comment]
SoftLayer Object Storage isn't directly supported by this client (at least not yet). Since it is based on OpenStack swift, most of the normal utilities and application should work normally.

Here's a link which I hope is useful: http://knowledgelayer.softlayer.com/procedure/how-do-i-access-object-storage-command-line
