### ISSUE TITLE
Using prompt_toolkit deprecated functions

### ISSUE THREAD

**Issue by kitterma** [softlayer/softlayer-python#675]
In prompt_toolkit 0.53 one of the functions was renamed.  It will still work for now since prompt_toolkit is providing a backward compatibility stub for now, but it'll need to be updated at some point.  I'd prepared a branch, but then I noticed the CLA requirement, so I can't submit it.

**Comment by sudorandom** [comment]
Sorry for the delay on this.

Which function were you talking about?

get_input() was renamed to prompt() in this commit: https://github.com/softlayer/softlayer-python/commit/ed7b2812cf411e1e62e38b955a685951d41f5603

I can't seem to find any other function names that are deprecated from prompt_toolkit. I think that commit might not have been released whenever you submitted this issue.

I'm going to close this since I think it's probably resolved. Feel free to re-open if it's still an issue.

**Comment by kitterma** [comment]
I think that was it.  Thanks.
