### ISSUE TITLE
Running Command `slcli vs detail` does not return `os_version`

### ISSUE THREAD

**Issue by joshku** [softlayer/softlayer-python#759]
### Expected Behavior
When running the detail command I expect to be shown the operating system and the version of the operating system as shown below.
```
:                 os : Ubuntu                               :
:         os_version : 14.04-64 Minimal for VSI             :
```
### Actual Behavior
When running the command only the operating system name is shown and the version is not shown like below
```
:                 os : Ubuntu                               :
:         os_version : -                                    :
```
### Environment Information
Operating System: Mac OSX El Capitan Version 10.11.6
softlayer-python version (`slcli --version`): 5.1.0

I was using softlayer-python version 4.1.1 and I got the expected behavior but when I recently upgraded to the latest 5.1.0 the operating version failed to show up. This behavior was shown for many of my virtual machines and I downgraded so that the functionality would return.

**Comment by sudorandom** [comment]
Very odd. This appears like an odd artifact of how masks work. The only difference between the two is an added part of a mask:

```python

+                '''softwareComponents[
+                    passwords[username,password,notes],
+                    softwareLicense[softwareDescription[name]]]''',
```

It seems that because we are looking at softwareLicenses with only the name selected in softwareComponents, that also effects softwareLicenses for operatingSystems.

I'll have a workaround fix for this soon, but I feel like this is a strange behavior or a bug in the API.
