### ISSUE TITLE
slcli block access-authorize --subnet-id

### ISSUE THREAD

**Issue by allmightyspiff** [softlayer/softlayer-python#860]
block storage is currently missing the ability to authorize a subnet ID. 
This feature seems to already be available for file storage.

**Comment by dpickle2** [comment]
Currently, the absence of the subnet option from the block access-authorize command is intentional. Authorizing subnets to block volumes is not supported on the backend due to several different limitations for block volumes that do not exist for file volumes.
I asked about this as well, and it sounds like there are no plans to add this ability in the foreseeable future.

**Comment by allmightyspiff** [comment]
ok thanks for the clarification, ill go ahead and close this issue then.
